---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-vms
  namespace: prometheus
  labels:
    app: node-exporter
subsets:
  - addresses:
      - ip: 172.29.29.5
    ports:
      - port: 9100
        name: metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-vms
  namespace: prometheus
  labels:
    app: node-exporter
spec:
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: metrics
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-vms-monitor
  namespace: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - prometheus
  jobLabel: external-vms
---
