apiVersion: v1
kind: Service
metadata:
  name: expose-redis-master
  namespace: redis-sentinel-test
spec:
  selector:
    master: "true"
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
